apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: badger-data
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-nfs
  volumeMode: Filesystem