resources:
  limits:
    memory: 100Mi
    cpu: 150m
  requests:
    memory: 75Mi
    cpu: 50m

# Settings for the Policy Reporter UI subchart (see subchart's values.yaml)
ui:
  enabled: true
  create: true
  plugins:
    kyverno: true
  resources:
    limits:
      memory: 256Mi
      cpu: 300m
    requests:
      memory: 50Mi
      cpu: 100m
  ingress:
    enabled: true
    ingressClassName: nginx-default
    annotations:
    hosts:
      - host: kyverno.hanxux.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: policy-reporter-tls-cert-secret
        hosts:
          - kyverno.hanxux.local

kyvernoPlugin:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      memory: 256Mi
      cpu: 300m
    requests:
      memory: 50Mi
      cpu: 100m

global:
  # available plugins
  plugins:
    # enable kyverno for Policy Reporter UI and monitoring
    kyverno: true

# Supported targets for new PolicyReport Results
target:
  loki:
    # loki host address
    host: "http://loki.monitoring.svc.cluster.local:3100"

    # loki api path, defaults to "/api/prom/push" (deprecated)
    path: "/loki/api/v1/push"
    # minimum priority "" < info < warning < critical < error
    minimumPriority: "warning"
    # list of sources which should send to loki
    sources:
    - kyverno
    - falco
