{
 "title": "AKS Local Platform Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "No of nodes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "description": "No of namespaces in the cluster",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(namespace)(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits)>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "stat",
   "description": "No of deployments",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_job_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "description": "No of deployments",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Secrets",
   "type": "stat",
   "description": "No of deployments",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_secret_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Volumes",
   "type": "stat",
   "description": "No of deployments",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kubelet_volume_stats_used_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "nodes"
    },
    {
     "expr": "sum (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate)",
     "legendFormat": "containers"
    },
    {
     "expr": "sum (namespace_cpu:kube_pod_container_resource_requests:sum)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (node_namespace_pod_container:container_memory_working_set_bytes)",
     "legendFormat": "used"
    },
    {
     "expr": "sum (namespace_memory:kube_pod_container_resource_requests:sum)",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum(container_fs_usage_bytes)", "legendFormat": "Used" },
    { "expr": "sum(container_fs_limit_bytes)", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[5m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total[5m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{code!~\"[245]..\"}[5m]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node) (\r\n    max by (namespace, pod, container, node) (\r\n        kube_pod_container_resource_requests{resource=\"cpu\",job=\"kube-state-metrics\"}\r\n    ) * on(namespace, pod) group_left() max by (namespace, pod) (\r\n        kube_pod_status_phase{phase=~\"Pending|Running\"} == 1\r\n    )\r\n) * 100 / sum by (node) (kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node) (\r\n    max by (namespace, pod, container, node) (\r\n        kube_pod_container_resource_requests{resource=\"memory\",job=\"kube-state-metrics\"}\r\n    ) * on(namespace, pod) group_left() max by (namespace, pod) (\r\n        kube_pod_status_phase{phase=~\"Pending|Running\"} == 1\r\n    )\r\n) * 100 / sum by (node) (kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "targets": [
    { "expr": "sum(kubelet_running_pods)", "legendFormat": "Pods" },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"pods\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{container_state=\"created\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_running_containers{container_state=\"exited\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_running_containers{container_state=\"running\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (kubelet_volume_stats_used_bytes)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum (kubelet_volume_stats_capacity_bytes)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Pods per namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas_available{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas_available{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas_unavailable{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(namespace) (kube_pod_owner{job=\"kube-state-metrics\"}) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{}) by (workload, namespace)) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace)(namespace_cpu:kube_pod_container_resource_requests:sum{}) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(namespace_cpu:kube_pod_container_resource_limits:sum{}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{}) by (namespace) / sum(namespace_cpu:kube_pod_container_resource_limits:sum{}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "API-Server - worker queue depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(workqueue_depth{job=\"apiserver\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true
  },
  {
   "title": "API-Server request rate (2xx)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\",code=~\"2..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Max Concurrent Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 39 },
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests)",
     "legendFormat": "max concurrent requests"
    }
   ]
  },
  {
   "title": "API-Server - work queue adds rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"apiserver\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "API-Server error rate (4xx/5xx)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\",code=~\"[45]..\"}[5m]))*100/sum(rate(apiserver_request_total{component=\"apiserver\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods CrashLooping",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 47 },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (sum_over_time(kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"}[15m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "API-Server latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    { "expr": "apiserver_request_duration_p95", "legendFormat": "__auto" },
    { "expr": "apiserver_request_duration_p99", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "API Server Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by (code) (rate(apiserver_request_terminations_total{resource =\"\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}