{
 "title": "Availability Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "targets": [
    { "expr": "absent(up==0)", "legendFormat": "__auto" },
    { "expr": "count(up==0) >bool 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kafka",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"}) >=bool 3",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"}) ==bool 2",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"}) ==bool 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "absent(kafka_server_replicamanager_leadercount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(up{namespace=\"monitoring\", pod=~\".*grafana.*\"}) >bool 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "absent(up{namespace=\"monitoring\", pod=~\".*grafana.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}