{
 "title": "Live Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(node)(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits)>0)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_running{namespace=\"zebra-fleet-manager\",container=\"online-events-decoder\"}) >=bool 1 or vector(0)",
     "legendFormat": "Kafka"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_running{namespace=~\"mismatch-.*-vcc\",container=\"map-mismatch-container\"}) >=bool 1 or vector(0)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_running{namespace=~\"mismatch-.*-zebra\",container=\"map-mismatch-container\"}) >=bool 1 or vector(0)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_running{namespace=\"mapapps\",container=\"map-delivery-storage\"}) >=bool 1 or vector(0)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_running{namespace=\"zebrafleetmap\",container=\"map-delivery-storage\"}) >=bool 1 or vector(0)",
     "legendFormat": "Kafka"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"rabbit\",container=\"rabbitmq\"}==1) >=bool 1 or vector(0)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"apicurio-schema-registry\",container=\"registry\"}==1) >=bool 1 or vector(0)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_running{namespace=\"monitoring\",container=\"prometheus\"}) >=bool 1 or vector(0)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_status_running{namespace=\"monitoring\",container=\"loki\"}) >=bool 1 or vector(0)",
     "legendFormat": "Value"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Crashing services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max by (namespace, container) (kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum by (container) (sum_over_time(loki:rule:errors:rate:1m[10m])*60 or vector(0) + sum_over_time(loki:rule:warnings:rate:1m[10m])*60 or vector(0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/Warnings Total",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum by (namespace, container) (sum_over_time(loki:rule:errors:rate:1m[$__range])*60 or vector(0) + sum_over_time(loki:rule:warnings:rate:1m[$__range])*60 or vector(0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Kafka - Top Topics",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by (topic) (kafka_log_log_size{namespace=\"kafka\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka - Top Topics",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (topic) (kafka_log_log_size{namespace=\"kafka\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki - Top Containers",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by (container) (sum_over_time(loki:rule:logs:bytes_rate:1m[$__range])*60))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki - Top Containers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (container) (sum_over_time(loki:rule:logs:bytes_rate:1m[$__range])*60))"
    }
   ]
  },
  {
   "title": "Top CPU Requests",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, container) (cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top CPU Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, container) (rate(container_cpu_usage_seconds_total{container!=\"\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Memory Requests",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, container) (cluster:namespace:pod_memory:active:kube_pod_container_resource_requests))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Memory Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace, container) (node_namespace_pod_container:container_memory_working_set_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Physical Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Kafka",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*kafka.*\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*kafka.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Loki",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*loki.*\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*loki.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Tempo",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*tempo.*\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*tempo.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*prometheus.*\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*prometheus.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Kafka Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*kafka.*\"}[5m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Loki Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*loki.*\"}[5m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Tempo Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*tempo.*\"}[5m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Prometheus Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*prometheus.*\"}[5m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Kafka Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total[5m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Log Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_log_messages_total[5m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Trace Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_traces_created_total[5m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Metrics Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total[5m]))",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}