{
 "title": "NGINX ModSecurity OWASP CRS",
 "description": "Dashboard to work with ModSecurity and the OWASP Coreruleset.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "apicurio-schema-registry,kafka-ui,map-delivery-web-ui,mapapps-tile-server-ingress,mimex-consumer-ingress,mimex-ingress,alertmanager,grafana,prometheus,oauth2-proxy,mqtt,sonarqube,event-control-request-service,probing-request-service,zebra-fleet-map-ingress"
   }
  ]
 },
 "panels": [
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Attackers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (client) (count_over_time({job=\"ingress-nginx/ingress-nginx\"} |= \"$service\" |= \"ModSecurity\" |= \"coreruleset\" | json date=\"transaction.time_stamp\", id=\"transaction.messages[0].details.ruleId\", client=\"transaction.client_ip\", server=\"transaction.request.headers.host\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "RuleId's at Vhost",
   "type": "stat",
   "gridPos": { "h": 18, "w": 9, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (server, msg, rule_id) (count_over_time({job=\"ingress-nginx/ingress-nginx\"} |= \"$service\" |= \"ModSecurity\" |= \"coreruleset\" | json date=\"transaction.time_stamp\", server=\"transaction.request.headers.host\", msg=\"transaction.messages[0].message\", rule_id=\"transaction.messages[0].details.ruleId\", client=\"transaction.client_ip\"| __error__=\"\" [$__interval]))",
     "legendFormat": "{{rule_id}}: {{msg}} {{server}}"
    }
   ]
  },
  {
   "title": "ModSec Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"ingress-nginx/ingress-nginx\"} |= \"$service\" |= \"ModSecurity\" |= \"coreruleset\" | json date=\"transaction.time_stamp\", client=\"transaction.client_ip\", server=\"transaction.request.headers.host\", request=\"transaction.request.method\", msg=\"transaction.messages[0].message\", level=\"transaction.messages[0].details.severity\" | __error__=\"\" [$__interval]))",
     "legendFormat": "Severity: {{level}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Logs  ➡️ only ModSecurity",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{job=\"ingress-nginx/ingress-nginx\"}|= \"$service\" |= \"ModSecurity\" |= \"coreruleset\" | json timestamp=\"transaction.time_stamp\", hostname=\"transaction.request.headers.host\", method=\"transaction.request.method\", ip=\"transaction.client_ip\", ruleset=\"transaction.producer.components[0]\", ruleid0=\"transaction.messages[0].details.ruleId\", message0=\"transaction.messages[0].message\", tag0=\"transaction.messages[0].details.tags\", ruleid1=\"transaction.messages[1].details.ruleId\", message1=\"transaction.messages[1].message\", tag1=\"transaction.messages[1].details.tags\", resource=\"transaction.request.uri\"\n\n| line_format \"🕗️ {{.timestamp}} 🌐 {{.method}} {{.hostname}} {{.resource}} \\n❗️☠️ ClientIP: {{.ip}} ☠️️❗️ ➡️ RuleSet: {{.ruleset }}\\n RuleId: {{.ruleid0}} {{.message0}} \\n🏷️ [tag {{.tag0}}] \\n➡️ RuleId: {{.ruleid1}} {{.message0}} \\n🏷️ [tag {{.tag1}}]  \""
      }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Exact Rule Infos",
     "type": "stat",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "topk (2, sum by (server, resource, rule_id, tags) (count_over_time({job=\"ingress-nginx/ingress-nginx\"}|= \"$service\" |= \"ModSecurity\" |= \"coreruleset\" | json server=\"transaction.request.headers.host\", resource=\"transaction.request.uri\", rule_id=\"transaction.messages[0].details.ruleId\", tags=\"transaction.messages[0].details.tags\", msg=\"transaction.messages[0].message\" | __error__=\"\" [$__interval])))",
       "legendFormat": "{{rule_id}}: {{server}}{{resource}} {{msg}}"
      }
     ]
    },
    {
     "title": "Error Logs all",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{job=\"ingress-nginx/ingress-nginx\"}"
      }
     ]
    }
   ]
  }
 ]
}