{
 "title": "Trivy Vulnerable images",
 "description": "Dashboard for Kube Trivy Exporter \nhttps://github.com/kaidotdev/kube-trivy-exporter\n\nFor image details install also this dashboard https://grafana.com/grafana/dashboards/12330",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'critical'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'high'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'medium'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM vulnerability\nWHERE\n  severity = 'low'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Unkown",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawSql": "SELECT\n  count(id) AS \"id\"\nFROM host",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Vulnerabilities Pie",
   "type": "piechart",
   "description": "sum(trivy_image_vulnerabilities) by (severity)",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities) by (severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 15, "w": 17, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort(sum(trivy_image_vulnerabilities) by (image_registry,image_repository,image_tag))",
     "legendFormat": "Image"
    },
    {
     "expr": "sort(sum(trivy_image_vulnerabilities{severity=\"Critical\"}) by (image_registry,image_repository,image_tag))",
     "legendFormat": "B"
    },
    {
     "expr": "sort(sum(trivy_image_vulnerabilities{severity=\"High\"}) by (image_registry,image_repository,image_tag))",
     "legendFormat": "B"
    }
   ]
  }
 ]
}