# should be updated if teams are added, team's object ID is changed in Azure
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   labels:
#     capsule-teams: "true"
#   namespace: kafka
#   name: kafka-editor
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: kafka-editor
# subjects:
# {{- range .Values.teams }}
# - apiGroup: rbac.authorization.k8s.io
#   kind: Group
#   name: {{ .azure_id }}
# {{- end }}

{{- if .Values.extended_port_forward }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    capsule-teams: "true"
  namespace: monitoring
  name: monitoring-port-forward
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-port-forward
subjects:
{{- range .Values.teams }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .name }}
{{- end }}
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   labels:
#     capsule-teams: "true"
#   namespace: apicurio-schema-registry
#   name: apicurio-port-forward
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: apicurio-port-forward
# subjects:
# {{- range .Values.teams }}
# - apiGroup: rbac.authorization.k8s.io
#   kind: Group
#   name: {{ .azure_id }}
# {{- end }}

{{- end }}
