apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kafkasql-journal
  labels:
    strimzi.io/cluster: kafka
  namespace: kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: -1
    segment.bytes: 10485760