apiVersion: v1
kind: Service
metadata:
  name: apicurio-schema-registry
  namespace: apicurio-schema-registry
  labels:
    app: apicurio-schema-registry
spec:
  selector:
    {{- include "apicurio-registry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: registry
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080