serviceMonitor:
  # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
  enabled: true

config:
  clients:
    - url: http://loki.monitoring.svc:3100/loki/api/v1/push

  snippets:
    extraScrapeConfigs: |
      - job_name: promtail-log-reader
        static_configs:
        - targets:
            - localhost
          labels:
            job: promtail-log-reader
            __path__: /var/log/pods/log-reader_log-reader-*/*/*.log
        pipeline_stages:
        - cri: {}
        - json:
            expressions:
              original_timestamp: original_timestamp
        - timestamp:
            source: original_timestamp
            format: Unix