name: Workflow Kafka Helm Charts

on:
  push:
    branches:
    - main
    paths:
    - 'kafka/**'
    - '.github/workflows/build-kafka-helm-charts.yml'
    - '.github/workflows/deploy-kafka-helm-charts.yml'
    - '.github/workflows/workflow-kafka.yml'
  # pull_request:
  #   branches:
  #   - main
  #   paths:
  #   - 'kafka/**'
  #   - '.github/workflows/build-kafka-helm-charts.yml'
  #   - '.github/workflows/deploy-kafka-helm-charts.yml'
  #   - '.github/workflows/workflow-kafka.yml'

  workflow_dispatch:

jobs:
  build-kafka-helm-charts:
    uses: ./.github/workflows/build-kafka-helm-charts.yml
    secrets: inherit

  deploy-kafka-helm-charts:
    needs: build-kafka-helm-charts
    uses: ./.github/workflows/deploy-kafka-helm-charts.yml
    secrets: inherit