apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: container-request-limit
  annotations:
    policies.kyverno.io/title: Request and Limit
    policies.kyverno.io/category: Resource and Reliability
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/description: >-
      Applying resource quotas and limit ranges at the namespace level helps
      prevent individual pods from monopolizing CPU resources.
      It ensures fair distribution and prevents excessive usage by specific workloads
spec:
  validationFailureAction: Audit
  background: false
  failurePolicy: Ignore
  rules:
  - name: check-container-resources
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "All containers must have CPU request and memory resource requests and limits defined."
      pattern:
        spec:
          containers:
          - name: "*"
            resources:
              limits:
                memory: "?*"
              requests:
                memory: "?*"
                cpu: "?*"
