acls:
  - resource:
      name: '*'
      patternType: literal
      type: topic
    operations:
      - Read
      - Write
      - Describe
      - DescribeConfigs
      - Alter
      - AlterConfigs
  - resource:
      name: '*'
      patternType: literal
      type: group
    operations:
      - Describe
      - Read
