reloader:
  deployment:
    # If you wish to run multiple replicas set reloader.enableHA = true
    replicas: 1
    resources:
      limits:
        cpu: "100m"
        memory: "512Mi"
      requests:
        cpu: "10m"
        memory: "72Mi"