apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-harbor
  namespace: harbor
spec:
  secretName: harbor-tls-cert-secret
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: ""
  privateKey:
    rotationPolicy: Always
  commonName: harbor.hanxux.local
  dnsNames:
    - harbor.hanxux.local
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
