apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-goldilocks
  namespace: goldilocks
spec:
  secretName: goldilocks-tls-cert-secret
  privateKey:
    rotationPolicy: Always
  commonName: goldilocks.hanxux.local
  dnsNames:
    - goldilocks.hanxux.local
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
