apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins
  namespace: jenkins
spec:
  secretName: jenkins-tls-cert-secret
  privateKey:
    rotationPolicy: Always
  commonName: jenkins.hanxux.local
  dnsNames:
    - jenkins.hanxux.local
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
