metrics:

  listen:
    port: 8080

  service:
    # -- Enable if you use another monitoring tool than Prometheus to scrape the metrics
    enabled: true

    # -- Metrics service port to scrape
    port: 8080

    # -- Additional service annotations
    annotations: {}

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 30m
      memory: 64Mi

certController:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 30m
      memory: 64Mi
