operator:
  # Docker registry used to pull Config Syncer operator image
  registry: harbor.hanxux.local
  # Config Syncer operator container image
  repository: platform-tools-local/appscode/kubed
  # Config Syncer operator container image tag
  tag: v0.13.2
  # Compute Resources required by the operator container
  resources:
    requests:
      cpu: 30m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 512Mi

replicaCount: 1

config:
  clusterName: local-platform
  additionalOptions:
    - resync-period=1m
