apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cert-manager
  namespace: monitoring
spec:
  groups:
    - name: cert-manager
      rules:
        - alert: CertManagerCertificateExpiration
          expr: (certmanager_certificate_expiration_timestamp_seconds - time()) / 60 / 60 / 24 < 7
          labels:
            severity: critical
            namespace: monitoring
          annotations:
            summary: "Less than 7 days before certificate expires"
            description: "Less than 7 days before let's encrypt certificate expires"
            runbook: ""
        - alert: CertManagerLateRenewal
          expr: (time() - min(certmanager_certificate_renewal_timestamp_seconds) by (name)) / 60 / 60 / 24 > 7
          labels:
            severity: warning
            namespace: monitoring
          annotations:
            summary: "Certificate should have been renewed 7 days ago"
            description: "Less than 7 days past certificate renewal due date"
            runbook: ""
