{
 "title": "AKS Local Kafka Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(count(kafka_server_replicamanager_leadercount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})[1h:5m]) - count(kafka_server_replicamanager_leadercount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kafka_server_replicamanager_leadercount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "description": "Number of topics in the cluster",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (topic) (kafka_log_log_size{namespace=\"kafka\"}))"
    }
   ]
  },
  {
   "title": "Partitions under minimum ISR",
   "type": "stat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |)",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Partitions at minimum ISR",
   "type": "stat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |)",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Online Replicas",
   "type": "stat",
   "description": "Replicas that are online",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{namespace=\"kafka\",strimzi_io_cluster=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kafka\",pod=~\"kafka-.*\",container=\"kafka\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min (sum(container_spec_memory_limit_bytes{namespace=\"kafka\",pod=~\"kafka-.*\",container=\"kafka\"}) by (pod))",
     "legendFormat": "Max memory, MB"
    },
    {
     "expr": "sum (jvm_memory_bytes_used{namespace=\"kafka\", container=\"kafka\"}) by (pod)",
     "legendFormat": "JVM {{pod}}"
    },
    {
     "expr": "min(sum (jvm_memory_bytes_max{namespace=\"kafka\", container=\"kafka\"}) by (pod))",
     "legendFormat": "Max JVM memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"kafka\",container=\"kafka\"}[1m]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"kafka\",container=\"kafka\"}))",
     "legendFormat": "MAX CPU"
    },
    {
     "expr": "sum by (pod) (rate(jvm_gc_collection_seconds_sum{namespace=\"kafka\",kubernetes_pod_name=~\"kafka-kafka.*\"}[5m]))",
     "legendFormat": "GC time {{pod}}"
    }
   ]
  },
  {
   "title": "Available Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"kafka\",persistentvolumeclaim=~\".*-kafka-kafka-.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (sum by (topic) (kafka_log_log_size{namespace=\"kafka\"}))",
     "legendFormat": "Log size"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum by (pod) (process_open_fds{namespace=\"kafka\",container=\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Segments",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kafka_log_log_numlogsegments)",
     "legendFormat": "Files"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Request total time",
   "type": "timeseries",
   "description": "The time is taken to process the message.\n\n- produce: requests from producers to send data\n- fetch-consumer: requests from consumers to get new data\n- fetch-follower: requests from brokers that are the followers of a partition to get new data\n\nUnder normal conditions, this value should be fairly static, with minimal fluctuations. If you are seeing anomalous behavior, you may want to check the individual queue, local, remote and response values to pinpoint the exact request segment that is causing the slowdown.\n\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (request) (kafka_network_requestmetrics_totaltimems{namespace=\"kafka\", request=~\"Produce|FetchConsumer|FetchFollower\", quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leader election rate",
   "type": "timeseries",
   "description": "This metric shows the time (ms) it takes to elect a new partition leader, i.e. the time a partition is without a leader. A non-zero value means there are broker failure.\n",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(kafka_controller_controllerstats_leaderelectionrateandtimems{quantile=\"0.99\"})",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Zookeeper request latency",
   "type": "timeseries",
   "description": "Clients can submit requests faster than ZooKeeper can process them, especially if there are a lot of clients. To prevent ZooKeeper from running out of memory due to queued requests, ZooKeeper will throttle clients so that there is no more than globalOutstandingLimit outstanding requests in the system. The default limit is 1,000.",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(zookeeper_avgrequestlatency{namespace=\"kafka\", memberType=\"Leader\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(zookeeper_maxrequestlatency{namespace=\"kafka\", memberType=\"Leader\"})",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Data rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{namespace=\"kafka\", topic != \"\"}[1m]))",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"kafka\", topic != \"\"}[1m]))",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "Incoming Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"kafka\", topic != \"\"}[1m]))",
     "legendFormat": "Messages"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"kafka\", topic != \"\"}[1m]))",
     "legendFormat": "Produce requests"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "(irate(kafka_server_kafkaserver_linux_disk_write_bytes{namespace=\"kafka\"}[1m]))",
     "legendFormat": "Write {{pod}}"
    },
    {
     "expr": "(irate(kafka_server_kafkaserver_linux_disk_read_bytes{namespace=\"kafka\"}[1m]))",
     "legendFormat": "Read {{pod}}"
    }
   ]
  },
  {
   "title": "Network total request rate",
   "type": "timeseries",
   "description": "You should monitor the rate of requests from your producers, consumers, and followers to ensure your Kafka deployment is communicating efficiently. You can expect Kafka’s request rate to rise as producers send more traffic or as your deployment scales out, adding consumers or followers that need to fetch messages. But if RequestsPerSec remains high, you should consider increasing the batch size on your producers, consumers, and/or brokers. This can improve the throughput of your Kafka deployment by reducing the number of requests, thereby decreasing unnecessary network overhead.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": " sum by (request) (irate(kafka_network_requestmetrics_requests_total{namespace=\"kafka\", request=~\"Produce|FetchConsumer|FetchFollower|CreateTopics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Kafka Broker & Zookeeper Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"kafka\",container=~\"kafka|zookeeper\"}[5m])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"kafka\"}[1m]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{namespace=\"kafka\"}[1m]))",
     "legendFormat": "Writes"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Topics",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_log_log_size{namespace=\"kafka\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (topic) (kafka_log_log_logendoffset - kafka_log_log_logstartoffset)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (topic) (kafka_log_log_numlogsegments)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(topic) (kafka_consumergroup_lag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purgatory size",
   "type": "timeseries",
   "description": "A request that is not fullfillable is added to purgatory and gets removed either by fuillfilling the request or by it timing out. \n\nKeeping an eye on the size of purgatory is useful to determine the underlying causes of latency. Increases in consumer fetch times, for example, can be easily explained if there is a corresponding increase in the number of fetch requests in purgatory.\n",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (delayedOperation) (kafka_server_delayedoperationpurgatory_numdelayedoperations{namespace=\"kafka\",delayedOperation=~\"Fetch|Produce\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zookeeper outstanding requests",
   "type": "stat",
   "description": "Clients can submit requests faster than ZooKeeper can process them, especially if there are a lot of clients. To prevent ZooKeeper from running out of memory due to queued requests, ZooKeeper will throttle clients so that there is no more than globalOutstandingLimit outstanding requests in the system. The default limit is 1,000.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{namespace=\"kafka\", memberType=\"Leader\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}