{
 "title": "Kyverno",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS_KYVERNO", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Latest Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming Admission Requests per seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_requests_total{}[2m]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Client Query to API-server (impersonate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kyverno_client_queries_total{operation=~\".*\"}[5m]))",
     "legendFormat": "request {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Policy-Rule Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Policies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"cluster\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"namespaced\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Generate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"generate\"}==1)"
    }
   ]
  },
  {
   "title": "Validate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"validate\"}==1)/count(kube_pod_info{pod=~\"kyverno-.*\", pod!~\"kyverno-cleanup-.*\"})"
    }
   ]
  },
  {
   "title": "Mutate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"mutate\"}==1)/count(kube_pod_info{pod=~\"kyverno-.*\", pod!~\"kyverno-cleanup-.*\"})"
    }
   ]
  },
  {
   "title": "Rule Execution Failure ( 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_result=\"fail\"}[24h]))*100/sum(increase(kyverno_policy_results_total{}[24h]))"
    }
   ]
  },
  {
   "title": "Scans Failure ( 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_results_total{rule_result=\"fail\", policy_background_mode=\"true\"}[24h]))*100/sum(increase(kyverno_policy_results_total{policy_background_mode=\"true\"}[24h]))"
    }
   ]
  },
  {
   "title": "Admission Review Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(rate(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}[5m]))by(rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(rate(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}[5m])) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Policy Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum(increase(kyverno_policy_results_total{rule_result=\"fail\"}[5m]))by(policy_name, policy_type))by(policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Admission Review Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(rate(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}[5m])) by (policy_type, rule_result)",
     "legendFormat": "{{policy_type}}-{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(increase(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}[5m])) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Policy-Rule Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Policies (by policy type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Policies (by policy validation action)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_validation_mode)) by (policy_validation_mode)",
     "legendFormat": "audit"
    }
   ]
  },
  {
   "title": "Active Policies running in background mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_background_mode=\"true\"}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Namespaced Policies (by namespaces)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_namespace!=\"-\"}==1) by (policy_name, policy_namespace)) by (policy_namespace)",
     "legendFormat": "{{policy_namespace}}"
    }
   ]
  },
  {
   "title": "Active Rules (by rule type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{}==1) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  {
   "title": "Policy-Rule Execution Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Rule Execution Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kyverno_policy_execution_duration_seconds_sum{}[5m])) by (rule_type) / sum(rate(kyverno_policy_execution_duration_seconds_count{}[5m])) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  {
   "title": "Average Policy Execution Latency Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 46 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kyverno_policy_execution_duration_seconds_sum{}[5m])) by (policy_type) / sum(rate(kyverno_policy_execution_duration_seconds_count{}[5m])) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Overall Average Rule Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_execution_duration_seconds_sum{}) / sum(kyverno_policy_execution_duration_seconds_count{})"
    }
   ]
  },
  {
   "title": "Overall Average Policy Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{}) by (policy_name, policy_type) / sum(kyverno_policy_execution_duration_seconds_count{}) by (policy_name, policy_type))"
    }
   ]
  },
  {
   "title": "Admission Review Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg - Admission Review Duration Over Time (by operation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_review_duration_seconds_sum{}[5m])) by (resource_request_operation) / sum(rate(kyverno_admission_review_duration_seconds_count{}[5m])) by (resource_request_operation)",
     "legendFormat": "Resource Operation: {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Avg - Admission Review Duration Over Time (by resource kind)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_review_duration_seconds_sum{}[5m])) by (resource_kind) / sum(rate(kyverno_admission_review_duration_seconds_count{}[5m])) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Avg - Overall Admission Review Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_admission_review_duration_seconds_sum{})/sum(kyverno_admission_review_duration_seconds_count{})"
    }
   ]
  },
  {
   "title": "Policy Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Changes Over Time (by change type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_changes_total{}[5m])) by (policy_change_type)",
     "legendFormat": "Change type: {{policy_change_type}}"
    }
   ]
  },
  {
   "title": "Policy Changes Over Time (by policy type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_changes_total{}[5m])) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Total Policy Changes (Last 24 Hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_policy_changes_total{}[24h]))"
    }
   ]
  },
  {
   "title": "Admission Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming Admission Requests per seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_requests_total{}[2m]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Admission Requests (24 Hours)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total{}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Requests (by resource kind)[per second]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_requests_total{}[5m])) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Admission Requests (by resource kind)[24h]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kyverno_admission_requests_total{}[24h])) by (resource_kind)",
     "legendFormat": "{{resource_kind}}"
    }
   ]
  },
  {
   "title": "Admission Requests (by operation)[per second]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_requests_total{}[2m]))by(resource_request_operation)",
     "legendFormat": "{{resource_request_operation}}"
    }
   ]
  }
 ]
}