{
 "title": "Madmaps: Map Delivery Logs",
 "description": "Logs from map delivery applications",
 "tags": [
  "mapapps",
  "map-delivery"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "madmap-compiler logs",
   "type": "logs",
   "description": "Logs from the compile job which compiles and ingests the map.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"mapapps\", container=\"compile\"} |= ``"
    }
   ]
  },
  {
   "title": "tile-delivery logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{namespace=\"mapapps\", container=\"tile-delivery\"} |= ``"
    }
   ]
  },
  {
   "title": "transport-agent-zebrafleet logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"mapapps\", container=\"transport-agent-zebrafleet\"} |= ``"
    }
   ]
  },
  {
   "title": "zebra-tile-consumer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{namespace=\"zebrafleetmap\", container=\"zebra-tile-consumer\"} |= ``"
    }
   ]
  },
  {
   "title": "source-map-download logs",
   "type": "logs",
   "description": "Last 15 minutes of source-map-download applicaiton logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{namespace=\"mapapps\", container=\"source-map-download\"} |= ``"
    }
   ]
  },
  {
   "title": "cloud-event-operator logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{namespace=\"mapapps\", container=\"cloud-event-operator\"} |= ``"
    }
   ]
  }
 ]
}