name: Helm Lint and Diff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  # Define kubeconfig file path and name
  KUBECONFIG: '${{ github.workspace }}/.kube/kubeconfig'
  # Define helm chart versions
  nginxVersion: 'helm-chart-4.10.1'
  configSyncerVersion: 'v0.13.2'
  externalDNSVersion: 'external-dns-helm-chart-1.14.4'
  certManagerVersion: 'v1.16.1'
  oauth2proxyVersion: 'oauth2-proxy-7.7.22'
  trivyOperatorVersion: 'trivy-operator-0.24.1'
  externalSecretsVersion: 'helm-chart-0.10.5'
  kyvernoVersion: 'kyverno-chart-3.2.7'
  policyReportVersion: 'policy-reporter-2.24.2'
  sonarqubeVersion: '10.3.0+2009'
  capsuleVersion: 'helm-v0.6.2'
  reloaderVersion: 'v1.0.115'


jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate kubeconfig from repository secret
        run: |
          mkdir -p '${{ github.workspace }}/.kube' \
          && echo '${{ secrets.HP_LOCAL_KUBECONFIG}}' | base64 -d > $KUBECONFIG \
          && chmod 600 $KUBECONFIG

      - name: Helm Lint Base
        run: |
          helm lint ./helm/base --values ./helm/base/values.yaml --kubeconfig $KUBECONFIG

      - name: Helm Lint Cert-manager Config
        run: |
          helm lint ./helm/cert-manager-config --values ./helm/cert-manager-config/values.yaml --kubeconfig $KUBECONFIG

      - name: Helm Lint Capsule Tenants
        run: |
          helm lint ./helm/capsule-tenants --values ./helm/capsule-tenants/values.yaml --kubeconfig $KUBECONFIG

      - name: Diff Cert-manager
        run: |
          export CHART_VERSION=${{env.certManagerVersion}}
          export VERSION=${CHART_VERSION#v}

          helm repo add jetstack https://charts.jetstack.io
          helm repo update jetstack

          helm diff upgrade cert-manager -n cert-manager \
            jetstack/cert-manager \
            -f ./external/cert-manager/values.yaml \
            --version $CHART_VERSION \
            --kubeconfig $KUBECONFIG

      # - name: Diff Config-syncer
      #   run: |
      #     export CHART_VERSION=${{env.configSyncerVersion}}
      #     export VERSION=${CHART_VERSION#v}

      #     helm repo add appscode https://charts.appscode.com/stable/
      #     helm repo update appscode

      #     helm diff upgrade config-syncer -n kube-system \
      #       appscode/kubed \
      #       --version $CHART_VERSION \
      #       -f ./external/config-syncer/values.yaml \
      #       --set config.additionalOptions="{--resync-period=30s}"

      - name: Diff Ingress-nginx
        run: |
          export CHART_VERSION=${{env.nginxVersion}}
          export VERSION=${CHART_VERSION#helm-chart-}

          curl -LOf https://github.com/kubernetes/ingress-nginx/releases/download/helm-chart-$VERSION/ingress-nginx-$VERSION.tgz

          helm diff upgrade ingress-nginx -n ingress-nginx \
            ingress-nginx-$VERSION.tgz \
            --version $VERSION \
            -f ./external/ingress-nginx/values.yaml \
            --kubeconfig $KUBECONFIG


      - name: Diff External DNS
        run: |
          export CHART_VERSION=${{env.externalDNSVersion}}
          export VERSION=${CHART_VERSION#external-dns-helm-chart-}

          helm repo add external-dns https://kubernetes-sigs.github.io/external-dns/
          helm repo update external-dns

          helm diff upgrade external-dns -n external-dns \
            external-dns/external-dns \
            --version $VERSION \
            -f ./external/external-dns/values.yaml \
            --kubeconfig $KUBECONFIG

      - name: Diff External Secrets
        run: |
          export CHART_VERSION=${{env.externalSecretsVersion}}
          export VERSION=${CHART_VERSION#helm-chart-}

          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update external-secrets

          helm diff upgrade external-secrets -n external-secrets \
            external-secrets/external-secrets \
            --version $VERSION \
            -f ./external/external-secrets/values.yaml \
            --kubeconfig $KUBECONFIG

      - name: Diff Oauth2-proxy
        run: |
          export CHART_VERSION=${{env.oauth2proxyVersion}}
          export VERSION=${CHART_VERSION#oauth2-proxy-}
          export REDIS_PASSWORD=$(kubectl get secret --namespace "oauth2-proxy" oauth2-proxy-redis --kubeconfig $KUBECONFIG -o jsonpath="{.data.redis-password}" | base64 -d)

          helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
          helm repo update oauth2-proxy

          helm diff upgrade oauth2-proxy -n oauth2-proxy \
            oauth2-proxy/oauth2-proxy \
            --version $VERSION \
            -f ./external/oauth2-proxy/values.yaml \
            --set config.clientID='${{ secrets.OAUTH2PROXY_CLIENT_ID}}' \
            --set config.clientSecret='${{ secrets.OAUTH2PROXY_CLIENT_SECRET}}' \
            --set config.cookieSecret='${{ secrets.OAUTH2PROXY_COOKIE_SECRET}}' \
            --set global.redis.password=$REDIS_PASSWORD \
            --kubeconfig $KUBECONFIG

      - name: Diff Trivy Operator
        run: |
          export CHART_VERSION=${{env.trivyOperatorVersion}}
          export VERSION=${CHART_VERSION#trivy-operator-}

          helm repo add aqua https://aquasecurity.github.io/helm-charts/
          helm repo update aqua

          helm diff upgrade trivy-operator -n trivy-system \
            aqua/trivy-operator \
            --version $VERSION \
            -f ./external/trivy-operator/values.yaml \
            --kubeconfig $KUBECONFIG

      - name: Diff Kyverno
        run: |
          export CHART_VERSION=${{env.kyvernoVersion}}
          export VERSION=${CHART_VERSION#kyverno-chart-}

          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm repo update kyverno

          helm diff upgrade kyverno -n kyverno \
            kyverno/kyverno \
            --version $VERSION \
            -f ./external/kyverno/values.yaml \
            --kubeconfig $KUBECONFIG

      - name: Diff Kyverno Policy Reporter
        run: |
          export CHART_VERSION=${{env.policyReportVersion}}
          export VERSION=${CHART_VERSION#policy-reporter-}

          helm repo add policy-reporter https://kyverno.github.io/policy-reporter
          helm repo update policy-reporter

          helm diff upgrade policy-reporter -n policy-reporter \
            policy-reporter/policy-reporter \
            --version $VERSION \
            -f ./external/policy-reporter/values.yaml \
            --kubeconfig $KUBECONFIG

      - name: Test Kyverno Policies
        run: |
          export PATH=$PATH:$KREW_ROOT/bin
          # To set pipeline to exit on any policy assessment failed, add `set -e`

          # Validate policies
          kubectl kyverno test . -f kyverno-test-image.yaml
          kubectl kyverno test . -f kyverno-test-resource.yaml
          kubectl kyverno test . -f kyverno-test-mutate-security.yaml
          kubectl kyverno test . -f kyverno-test-validate-security.yaml
          kubectl kyverno test . -f kyverno-test-validate-security-baseline.yaml
          kubectl kyverno test . -f kyverno-test-traceability.yaml

#TBD - Check 2 policy failed
# │────│─────────────────────────────────────│──────────────────────│────────────────────────────────│────────│─────────────────────│
# │ ID │ POLICY                              │ RULE                 │ RESOURCE                       │ RESULT │ REASON              │
# │────│─────────────────────────────────────│──────────────────────│────────────────────────────────│────────│─────────────────────│
# │ 1  │ disallow-latest-tag-external-images │ validate-image-tag-d │ Deployment/kyverno-test-latest │ Fail   │ Want pass, got fail │
# │ 2  │ disallow-latest-tag-pod             │ validate-image-tag   │ Pod/kyverno-test-latest        │ Fail   │ Want pass, got fail │
# │────│─────────────────────────────────────│──────────────────────│────────────────────────────────│────────│─────────────────────│