name: helm lint and diff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


defaults:
  run:
    shell: bash
    #working-directory: /home/s0001969/Cloud/local-k8s-platform-tools

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    env:
      KUBECONFIG: '${{ github.workspace }}.kube/kubeconfig'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate kubeconfig from secret
        run: |
          mkdir -p '${{ github.workspace }}/.kube' \
          && echo '${{ secrets.HP_LOCAL_KUBECONFIG}}' | base64 -d > $KUBECONFIG

      - name: Helm Lint Base
        run: |
          helm lint ./helm/base --values ./helm/base/values.yaml --kubeconfig '$KUBECONFIG'

      - name: Helm list harbor
        run: |
          helm list -n harbor --kubeconfig '$KUBECONFIG'

      - name: check nodes
        run: |
          kubectl get nodes --kubeconfig '$KUBECONFIG'
